#!/bin/sh

package_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
export LD_LIBRARY_PATH="${package_dir}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export QT_PLUGIN_PATH="${package_dir}/plugins${QT_PLUGIN_PATH:+:${QT_PLUGIN_PATH}}"
exec "${package_dir}/bin/transfer" "$@"
